### ISSUE TITLE
Persistence

### ISSUE THREAD

**Issue by h4llow3En** [tracktor-one/tracktor#5]
Make everything persistent with diesel.rs

Wich database should be used? Postgres, MySQL or SQLite?

**Comment by MarauderXtreme** [comment]
I would pledge for Postgres first or MariaDB second.

Is it possible to create some kind of abstraction layer to use whatever database is put under the software?

**Comment by h4llow3En** [comment]
you have to configure it in the cargo.toml. But I will have a look, how we could make both happen. The basic abstraction layer is given by [diesel](http://diesel.rs/guides/getting-started/) itself
